title: Firecall </> by GochoMugo
project_name: firecall
description: >
  A Python helper library for Firebase.
repository_url: https://github.com/GochoMugo/firecall
repository_shorthand: GochoMugo/firecall

baseurl: /firecall

author_name: GochoMugo
author_url: https://github.com/GochoMugo

markdown: kramdown
